language: csharp
mono: none
dotnet: 2.0.0
solution: PodcastManager.sln
before_install:
  - sudo apt-get install nunit-console
after_script:
  - nunit-console ManagersApi.Tests/bin/Release/ManagersApi.Tests.dll
script:
  - cd PodcastManager
  - dotnet restore
  - dotnet build -c Release
  - cd ..
  - cd ManagersApi.Tests
  - dotnet restore
  - xbuild /p:Configuration=Release ManagersApi.Tests.csproj /p:TargetFrameworkVersion="v4.6.1"
  - cd ..